# Generated by Django 3.2.12 on 2022-04-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_store_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_photo',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
